# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name:Default
  #demands:agent.os -equals Darwin

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  inputs:
    script: 'deploy-application.bat
      application_path:"C:Users\shivanshoo.yadav\Downloads\_work\DMR.zip"
      username:Shivanshoo
      password:qwerty@203
      url:https://saggezza-demo.appiancloud.com/suite'